apiVersion: v1
kind: Pod
metadata:
  name: mwmp
spec:
  containers:
  - image: docker.io/library/mysql:8
    name: mysql
    env:
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_ROOT_PASSWORD
      value: root
  - image: docker.io/library/wordpress:5
    name: wordpress
    env:
    - name: WORDPRESS_DB_HOST
      value: 0.0.0.0
    - name: WORDPRESS_DB_PASSWORD
      value: root
    ports:
    - containerPort: 80
      hostPort: 8080